# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:6.9.4

clone:
  depth: full

pipelines:
  default:
    - step:
        name: Build the project
        caches: # Cache node_modules directory, sonarcloud and node-scanner
          - node
          - sonarcloud
          - node-scanner
        script:
          - npm install
          - npm install -g sonarqube-scanner
          - sonar-scanner

definitions:
  caches:
    sonarcloud: ~/.sonar/cache
    node-scanner: ~/.sonar/native-sonar-scanner
